### PR TITLE
Replace landing logo with new one

### PR DESCRIPTION
**Pull request by thomasbruketta**

### CODE REVIEW

**Comment by kylpo** [comment]
Yo, that'll help with the home screen, but not the loading screen. Mind fixing that one, too? Otherwise, I'd prefer keeping the broken one since I have a transition from loading to home screen that relies on the logos being identical.

Thanks!

**Comment by thomasbruketta** [comment]
Good call. Will do.

**Comment by kylpo** [comment]
Thanks!

**Comment by thomasbruketta** [comment]
@kylpo updated. I had to set fixed width on the image to make sure it would work for 7 and 7plus. It was previously filling the device width which made for some funny sub pixel math on the splash screen.

**Comment by kylpo** [comment]
Looks great - thanks! 👍

**Pull request merged**
